### ISSUE TITLE
GoogleUserCircleAvatar breaking behaviour change

### ISSUE THREAD

**Issue by gbaccetta** [efortuna/memechat#24]
Hello, this does not work anymore:
const GoogleUserCircleAvatar(
  String profileImageUrl,
);

source: https://groups.google.com/forum/#!topic/flutter-dev/7MRiSpxDeo0

**Comment by gbaccetta** [comment]
To make the sample works I replaced in line 234:

 `child: new GoogleUserCircleAvatar(message.sender.imageUrl),`

with:

 `child: new CircleAvatar(backgroundImage: new NetworkImage(message.sender.imageUrl),`

**Comment by wangvic** [comment]
This works for me. Thank you.
