### ISSUE TITLE
iOS Build fails with Firebase error

### ISSUE THREAD

**Issue by viju85** [efortuna/memechat#25]
I get an error when building iOS even after I have the GoogleService-Info.plist under memechat/ios/Runner/

[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.

Note: I had to add the below into my Info.plist:
`<key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>com.blahblah.memechat</string>
                                <string>[REAL REVERSED_CLIENT_ID]</string>
                        </array>
                </dict>
        </array>`

**Comment by hnvn** [comment]
Open Xcode project (Runner), then add GoogleService-Info.plist file to your project

**Comment by efortuna** [comment]
Hi @viju85, as @hnvn mentioned, if you open Runner in Xcode and add it that way, it will automatically make that change to your Info.plist. I'm glad you figured it out!

(and @viju85, nice meeting you at I/O!)
