### ISSUE TITLE
keytool password is missing in README.md

### ISSUE THREAD

**Issue by Soundbytes** [efortuna/memechat#30]
When following the instructions in readme.md at one point a password is required for the creation of the SHA-1 key. Since the code example is targeted at beginners (like myself) I thougt it might be nice to include the password (it's `android` BTW)
Thanks!

**Comment by efortuna** [comment]
Hi Soundbytes,
Thanks for checking out the code! The password that you specify for the SHA-1 key is something that _you_ set yourself. It's a little like your login password, so it's different for everyone, and not something I can really add to the README. Just so you know, you can create a SHA-1 key without a password by just hitting "enter" when it prompts for a password.

**Comment by Soundbytes** [comment]
Oh thanks! It wasn't obvious that you can just omit the password.
