### ISSUE TITLE
java.lang.Exception: Only one command is allowed: both -exportcert and -list were specified.

### ISSUE THREAD

**Issue by zephyo** [efortuna/memechat#40]
Hi, cool app! When trying to follow the Android Setup instructions, I get:

```
keytool -exportcert -list -v \
> -alias androiddebugkey -keystore ~/.android/debug.keystore
keytool error: java.lang.Exception: Only one command is allowed: both -exportcert and -list were specified.
```

**Comment by chonghorizons** [comment]
This is just a twolines issue.

Type this:
`keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android`

Or read more here: 
https://stackoverflow.com/questions/30070264/get-sha1-fingerprint-certificate-in-android-studio-for-google-maps


Proposed:  @zephyo Close this issue if it works.
